# Generated by Django 4.2.6 on 2023-10-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
