# Generated by Django 4.2.6 on 2023-10-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='Semail',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
