# Generated by Django 4.2.6 on 2023-10-13 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0002_remove_doctor_dpid_remove_doctor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dpid', models.AutoField(primary_key=True, serialize=False)),
                ('Dpname', models.CharField(max_length=50)),
                ('Dphead', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Dname', models.CharField(max_length=50)),
                ('Dgender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('Dphone', models.PositiveIntegerField()),
                ('Daddress', models.CharField(max_length=100)),
                ('Dsalary', models.PositiveIntegerField()),
                ('Demail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Dpassword', models.CharField(max_length=30)),
                ('Ddob', models.DateField(max_length=8)),
                ('Qualification', models.CharField(max_length=50)),
                ('Specialisation', models.CharField(max_length=50)),
                ('Dpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
