# Generated by Django 4.2.6 on 2023-10-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('hospital', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MR',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.CharField(max_length=100)),
                ('rdate', models.DateField(max_length=8)),
                ('rtime', models.TimeField()),
                ('Demail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('Pemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=50)),
                ('Adate', models.DateField(max_length=8)),
                ('Atime', models.TimeField()),
                ('Demail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('Pemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
