# Generated by Django 4.2.6 on 2023-10-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0014_initial'),
        ('Doctor', '0003_initial'),
        ('Admin', '0008_remove_mr_demail_remove_mr_pemail_delete_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MR',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.CharField(max_length=100)),
                ('rdate', models.DateField(max_length=8)),
                ('rtime', models.TimeField()),
                ('Demail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('Pemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('Ptname', models.CharField(max_length=50)),
                ('Ptphone', models.CharField(max_length=10)),
                ('issue', models.CharField(max_length=50)),
                ('Adate', models.DateField(max_length=8)),
                ('Atime', models.TimeField(null=True)),
                ('Status', models.CharField(choices=[('Confirm', 'Confirm'), ('Decline', 'Decline')], max_length=7)),
                ('Demail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('Dpname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.department')),
                ('Pemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
