# Generated by Django 4.2.6 on 2023-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_appointment_dpname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mr',
            name='Patientname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
