# Generated by Django 4.2.6 on 2023-10-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_mr_patientname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Dpname',
            new_name='Dpid',
        ),
    ]
