# Generated by Django 4.2.6 on 2023-10-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dpid', models.AutoField(primary_key=True, serialize=False)),
                ('Dpname', models.CharField(max_length=50)),
                ('Dphead', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=50)),
                ('Dgender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('Dphone', models.IntegerField(max_length=10)),
                ('Daddress', models.CharField(max_length=100)),
                ('Dsalary', models.PositiveIntegerField()),
                ('Demail', models.EmailField(max_length=254)),
                ('Ddob', models.DateField(max_length=8)),
                ('Qualification', models.CharField(max_length=50)),
                ('Specialisation', models.CharField(max_length=50)),
                ('Dpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=50)),
                ('Pgender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('Paddresss', models.CharField(max_length=100)),
                ('Pphone', models.IntegerField(max_length=10)),
                ('Pdob', models.DateField(max_length=8)),
                ('Pemail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=50)),
                ('Sgender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('Saddresss', models.CharField(max_length=100)),
                ('Sphone', models.IntegerField(max_length=10)),
                ('Sdob', models.DateField(max_length=8)),
                ('Semail', models.EmailField(max_length=254)),
                ('Sjob', models.CharField(max_length=50)),
                ('Ssalary', models.PositiveIntegerField()),
                ('Dpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
            ],
        ),
        migrations.CreateModel(
            name='MR',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.CharField(max_length=100)),
                ('rdate', models.DateField(max_length=8)),
                ('rtime', models.TimeField()),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=50)),
                ('Adate', models.DateField(max_length=8)),
                ('Atime', models.TimeField()),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
