# Generated by Django 4.2.6 on 2023-10-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Dphone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Pphone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Sphone',
            field=models.PositiveIntegerField(),
        ),
    ]
