# Generated by Django 4.2.6 on 2023-10-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
