# Generated by Django 4.2.6 on 2023-10-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_doctor_user_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Dpid',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='Did',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='Pid',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Dpid',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='MR',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
