# Generated by Django 4.2.6 on 2023-10-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Dpid',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Pemail',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='Demail',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='Pemail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Dpid',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='MR',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
