# Generated by Django 4.2.6 on 2023-10-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_mr_demail_remove_mr_pemail_delete_appointment_and_more'),
        ('hospital', '0012_alter_patient_pgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
