# Generated by Django 4.2.6 on 2023-10-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0013_remove_patient_user_delete_feedback_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Pname', models.CharField(max_length=50)),
                ('Pgender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('Paddresss', models.CharField(max_length=100)),
                ('Pphone', models.PositiveIntegerField()),
                ('Pdob', models.DateField(max_length=8)),
                ('Pemail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Ppassword', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=250)),
                ('fdatetime', models.DateTimeField(auto_now_add=True)),
                ('Pemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
