# Generated by Django 4.2.6 on 2023-10-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_remove_feedback_fdatetime_feedback_fdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ftime',
        ),
    ]
