# Generated by Django 4.2.6 on 2023-10-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_feedback_fdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='fdate',
        ),
    ]
